spring.application.name=userdemo
server.port = 8081

spring.datasource.url=jdbc:mysql://localhost:3306/milendb
spring.datasource.username=root
spring.datasource.password=milen1211

spring.jpa.hibernate.ddl-auto=update