spring.application.name = orderSpring

server.port = 8081

spring.datasource.url = jdbc:mysql://localhost:3306/springinventorydb
spring.datasource.username = root
spring.datasource.password = milen1211

spring.jpa.hibernate.ddl-auto = update

spring.messages.basename = messages
spring.messages.encoding = UTF-8