spring.application.name=springMilen
server.port = 8081

spring.datasource.url = jdbc:mysql://localhost:3306/springdemodb
spring.datasource.username = root
spring.datasource.password = milen1211

spring.jpa.hibernate.ddl-auto = update

spring.messages.basename = messages

#spring.security.user.name = admin
#spring.security.user.password = password

spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8080/realms/spring-dev

keycloak.server-url = http://localhost:8080
keycloak.realm = spring-dev
keycloak.client-id = spring-client
keycloak.client-secret = I1tCwXrKUYrVzTcKW0HkDGNpdtvjaomW

#logging.level.root=INFO
#
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
#logging.level.org.springframework.security.oauth2.server.resource=DEBUG
#logging.level.org.springframework.web=DEBUG
