spring.application.name=userLogin
server.port = 8081

spring.datasource.url = jdbc:mysql://localhost:3306/springdemodb
spring.datasource.username = root
spring.datasource.password = milen1211

spring.jpa.hibernate.ddl-auto = update

spring.messages.basename = messages

keycloak.server-url = http://localhost:8080
keycloak.realm = spring-dev
keycloak.client-id = spring-client
keycloak.client-secret = I1tCwXrKUYrVzTcKW0HkDGNpdtvjaomW

log.service-url = http://localhost:8082
