package com.example.demo.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * User Response DTO - Data Transfer Object for outgoing responses
 * 
 * This DTO is returned to clients from both GET and POST endpoints.
 * 
 * Why separate Response DTO?
 * 1. Control what data is exposed to clients
 * 2. Can include computed fields or aggregated data
 * 3. Different from entity (e.g., never expose password)
 * 4. Can flatten nested relationships
 * 
 * @Data - Lombok: Generates getters, setters, toString, equals, hashCode
 * @Builder - Lombok: Enables builder pattern for easy object creation
 * @NoArgsConstructor - Required for some serialization frameworks
 * @AllArgsConstructor - Required for builder pattern
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserResponseDTO {
    
    /**
     * User ID - Auto-generated by database
     */
    private Long id;
    
    /**
     * User's name
     */
    private String name;
    
    /**
     * User's email
     */
    private String email;
    
    /**
     * User's age
     */
    private Integer age;
    
    /**
     * When the user record was created
     */
    @CreationTimestamp
    private LocalDateTime createdAt;
    
    /**
     * When the user record was last updated
     */
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}